language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install python-coveralls
# command to run tests
script:
  - py.test CreditCardValidation.py < test.txt --cov coveralls

after_success:
  - TRAVIS_TEST_RESULT
  - coveralls