language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install coveralls
# command to run tests
script:
  - pytest test_CreditCardValidation.py < test.txt 
   
after_success:
  - TRAVIS_TEST_RESULT
  - coveralls